# Generated by Django 5.2.8 on 2025-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
            ],
        ),
    ]
